name: Build Electron App

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build App for Linux and macOS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build for Linux
        run: npx electron-forge make --platform=linux

      - name: Navigate to Linux Build Directory
        run: cd out/make/linux

      - name: Create Linux Zip
        run: zip -r linux-build.zip .

      - name: Move Linux Zip to Workspace
        run: mv linux-build.zip ../../

      - name: Build for macOS
        run: npx electron-forge make --platform=darwin

      - name: Navigate to macOS Build Directory
        run: cd out/make/darwin

      - name: Create macOS Zip
        run: zip -r mac-build.zip .

      - name: Move macOS Zip to Workspace
        run: mv mac-build.zip ../../

      - name: Upload Linux Build Zip
        uses: actions/upload-artifact@v2
        with:
          name: linux-build
          path: linux-build.zip

      - name: Upload macOS Build Zip
        uses: actions/upload-artifact@v2
        with:
          name: mac-build
          path: mac-build.zip
